In [ ]:
#TASK-1(Lists, Dictionaries and Tuples)

In [1]:

nums = [3, 5, 7, 8, 12]
print(f"\nQuestion-1.1")
cube = []
for i in nums:
    cube.append(i*i*i)
print( cube)


Question-1.1
[27, 125, 343, 512, 1728]


In [2]:
print(f"\nQuestion-1.")
dict = {}
print("original dictionary: ", dict)

dict['parrot'] = 2 
dict['goat'] = 4 
dict['spider'] = 8  
dict['crab'] = 10 

print("updated dictionary: ", dict)

original dictionary:  {}
updated dictionary:  {'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}


In [3]:
print(f"\nQuestion-1.3")
res = 0
for key, value in dict.items():
   
    print(f"Animal:{key}    Legs:{value}")
    res += value
print("sum of legs",res)

Animal:parrot    Legs:2
Animal:goat    Legs:4
Animal:spider    Legs:8
Animal:crab    Legs:10
sum of legs 24


In [4]:
print(f"\nQuestion-1.4")
A = (3, 9, 4,[5,6])
print(A)

A[3][0] = 8
print(A)

(3, 9, 4, [5, 6])
(3, 9, 4, [8, 6])


In [6]:

print(f"\nQuestion-1.5")
del A

In [2]:
print(f"\nQuestion-1.6")
B = ('a', 'p', 'p', 'l', 'e')
print(B.count('p'))


Question-1.6
2


In [14]:
print(f"Question-1.7")
B = ('a', 'p', 'p', 'l', 'e')
print(B.index('l'))

3


In [ ]:
#TASK-2(Numpy)

In [1]:
print("\nQuestion-2.1")
import numpy as np # type: ignore
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(A)


Question-2.1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print("\nQuestion-2.2")
b = A[:2, :2]
print(b)

In [3]:
print("\nQuestion-2.3")
C = np.zeros_like(A)
print(C)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [4]:
print("\nQuestion-2.4")
z = np.array([1, 0, 1])
for i in range(A.shape[1]): 
    C[:, i] = A[:, i] + z  
print(C)

[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [5]:
print("\nQuestion-2.5")
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
v = np.array([9,10])
sum_result = X+Y
print("Sum of X and Y is:", sum_result)

Sum of X and Y is: [[ 6  8]
 [10 12]]


In [6]:
print("\nQuestion-2.6")
mul_result = X*Y
print("Product of X and Y is:", mul_result)

Product of X and Y is: [[ 5 12]
 [21 32]]


In [7]:
print("\nQuestion-2.7")
sqrt_result = np.sqrt(Y)
print("Elemant wise square root of X and Y is:", sqrt_result)

Elemant wise square root of X and Y is: [[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [8]:
print("\nQuestion-2.8")
dot_p_result = np.dot(X, v)
print("Product of X and v is:", dot_p_result)

Product of X and v is: [29 67]


In [9]:
print("\nQuestion-2.9")
column_s_result = np.sum(X, axis=0) #For row axis=1
print("Sum of each column of X:\n", column_s_result)


Question-2.9
Sum of each column of X:
 [4 6]


In [ ]:
#TASK-3(Functions and Loops)

In [1]:
print("\nQuestion-3.1")
def Compute(Dis, T):
    Vel = Dis / T
    return Vel
distance = 80
time = 4
Vel = Compute(distance, time)
print(f"The velocity is {Vel} m/s.")


Question-3.1
The velocity is 20.0 m/s.


In [2]:
print("\nQuestion-3.2")

even_num = [2, 4, 6, 8, 10, 12]
def mult(even_num):
    product = 1
    for num in even_num:
        product *= num
    return product
product_of_even_num = mult(even_num)
print(product_of_even_num)


Question-3.2
46080


In [ ]:
#TASK-4(PANDA)

In [1]:
print("Question-4.1")
import pandas as pd
d = {'C1': [1, 2, 3, 5, 5], 'C2': [6, 7, 5, 4, 8], 'C3': [7, 9, 8, 6, 5],'C4': [7, 5, 2, 8, 8],}
df = pd.DataFrame(data=d)
print(df)

Question-4.1
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [2]:
print("Question-4.1")
print (df.head(2))

Question-4.1
   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [3]:
print("Question-4.2")
print(df['C2'])

Question-4.2
0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [4]:
print("Question-4.3")
df.rename(columns={'C3': 'B3'}, inplace=True)
print(df)

Question-4.3
   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [7]:
print("Question-4.4")
lst = df.sum()
df['Sum'] = lst
print(df)

Question-4.4
   C1  C2  B3  C4  Sum
0   1   6   7   7  NaN
1   2   7   9   5  NaN
2   3   5   8   2  NaN
3   5   4   6   8  NaN
4   5   8   5   8  NaN


In [8]:
df['Sum'] = df.sum(axis=1)
print(df)

   C1  C2  B3  C4   Sum
0   1   6   7   7  21.0
1   2   7   9   5  23.0
2   3   5   8   2  18.0
3   5   4   6   8  23.0
4   5   8   5   8  26.0


In [16]:
print("Question-4.6")
df = pd.read_csv(r'hello_sample.csv')


In [17]:
print("Question-4.7")
print(df.to_string())

    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [18]:
print("Question-4.8")
print(df.tail(2))

   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [19]:
print("Question-4.9")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes
None


In [20]:
print(df.shape)

(23, 4)


In [21]:
print("Question-4.10")
df_sorted = df.sort_values(by='Weight')
print(df_sorted)

    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [22]:
print("Question-4.11")
print(df.isnull())

    Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False


In [23]:
print("Question-4.12")
print(df.dropna())


    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66
